# Generated by Django 5.2.14 on 2026-07-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posthog", "1256_userproductlist_default_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="sharingconfiguration",
            name="auto_refresh_interval",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (0, "Disabled"),
                    (1800, "30 minutes"),
                    (3600, "1 hour"),
                    (5400, "1.5 hours"),
                    (21600, "6 hours"),
                ],
                help_text="Shared dashboard auto-refresh interval in seconds. Null preserves the legacy 30-minute default.",
                null=True,
            ),
        ),
    ]
