import { MakeLogicType, actions, afterMount, connect, kea, key, listeners, path, props, reducers, selectors } from 'kea'
import { forms } from 'kea-forms'
import { loaders } from 'kea-loaders'

import api from 'lib/api'
import { preflightLogic } from 'lib/logic/preflightLogic'
import { eventUsageLogic } from 'lib/utils/eventUsageLogic'
import { getInsightId } from 'scenes/insights/utils'
import { organizationLogic } from 'scenes/organizationLogic'
import { urls } from 'scenes/urls'
import { userLogic } from 'scenes/userLogic'

import type { AutoRefreshIntervalEnumApi, SharingConfigurationApi } from '~/generated/core/api.schemas'
import { dashboardsModel } from '~/models/dashboardsModel'
import { AvailableFeature, InsightShortId, OrganizationType } from '~/types'

import type { DeepPartial, DeepPartialMap, FieldName, ValidationErrorType } from 'kea-forms'

export interface SharingLogicProps {
    dashboardId?: number
    insightShortId?: InsightShortId
    recordingId?: string
    notebookShortId?: string
    additionalParams?: Record<string, any>
}

export interface EmbedConfig {
    width: string
    height: string
}

const defaultIframeConfig = {
    width: '100%',
    height: '400',
}

const defaultSharingSettings = {
    whitelabel: false,
    legend: false,
    noHeader: false,
    showInspector: false,
    hideExtraDetails: false,
    theme: 'system',
}

const propsToApiParams = async (
    props: SharingLogicProps
): Promise<{
    dashboardId?: number
    insightId?: number
    recordingId?: string
    notebookShortId?: string
}> => {
    const insightId = props.insightShortId ? await getInsightId(props.insightShortId) : undefined
    return {
        dashboardId: props.dashboardId,
        insightId,
        recordingId: props.recordingId,
        notebookShortId: props.notebookShortId,
    }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface sharingLogicValues {
    accessControlAvailable: any;
    embedCode: string;
    embedLink: string;
    iframeKey: number;
    iframeProperties: {
        allowFullScreen: true;
        frameBorder: number;
        height: string;
        key: number;
        sandbox: string;
        src: string;
        width: string;
    };
    isSharingSettingsSubmitting: boolean;
    isSharingSettingsValid: boolean;
    params: any;
    shareLink: string;
    sharingAllowed: boolean;
    sharingConfiguration: SharingConfigurationApi | null;
    sharingConfigurationLoading: boolean;
    sharingSettings: {
        hideExtraDetails: boolean;
        legend: boolean;
        noHeader: boolean;
        showInspector: boolean;
        theme: string;
        whitelabel: boolean;
    };
    sharingSettingsAllErrors: Record<string, any>;
    sharingSettingsChanged: boolean;
    sharingSettingsErrors: DeepPartialMap<{
        hideExtraDetails: boolean;
        legend: boolean;
        noHeader: boolean;
        showInspector: boolean;
        theme: string;
        whitelabel: boolean;
    }, ValidationErrorType>;
    sharingSettingsHasErrors: boolean;
    sharingSettingsManualErrors: Record<string, any>;
    sharingSettingsTouched: boolean;
    sharingSettingsTouches: Record<string, boolean>;
    sharingSettingsValidationErrors: DeepPartialMap<{
        hideExtraDetails: boolean;
        legend: boolean;
        noHeader: boolean;
        showInspector: boolean;
        theme: string;
        whitelabel: boolean;
    }, ValidationErrorType>;
    showPreview: boolean;
    showSharingSettingsErrors: boolean;
    siteUrl: string | undefined;
    whitelabelAvailable: any;
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface sharingLogicActions {
    loadSharingConfiguration: () => any;
    loadSharingConfigurationFailure: (error: string, errorObject?: any) => {
        error: string;
        errorObject?: any;
    };
    loadSharingConfigurationSuccess: (sharingConfiguration: SharingConfigurationApi | null, payload?: any) => {
        sharingConfiguration: SharingConfigurationApi | null;
        payload?: any;
    };
    reloadIframe: () => {
        value: true;
    };
    resetSharingSettings: (values?: {
        hideExtraDetails: boolean;
        legend: boolean;
        noHeader: boolean;
        showInspector: boolean;
        theme: string;
        whitelabel: boolean;
    }) => {
        values?: {
            hideExtraDetails: boolean;
            legend: boolean;
            noHeader: boolean;
            showInspector: boolean;
            theme: string;
            whitelabel: boolean;
        };
    };
    setAutoRefreshInterval: (auto_refresh_interval: AutoRefreshIntervalEnumApi) => AutoRefreshIntervalEnumApi;
    setAutoRefreshIntervalFailure: (error: string, errorObject?: any) => {
        error: string;
        errorObject?: any;
    };
    setAutoRefreshIntervalSuccess: (sharingConfiguration: SharingConfigurationApi | null, payload?: AutoRefreshIntervalEnumApi) => {
        sharingConfiguration: SharingConfigurationApi | null;
        payload?: AutoRefreshIntervalEnumApi;
    };
    setIsEnabled: ({
                    enabled,
                    onSuccess,
                }: {
        enabled: boolean;
        onSuccess?: (enabled: boolean) => void;
    }) => {
        enabled: boolean;
        onSuccess?: (enabled: boolean) => void;
    };
    setIsEnabledFailure: (error: string, errorObject?: any) => {
        error: string;
        errorObject?: any;
    };
    setIsEnabledSuccess: (sharingConfiguration: SharingConfigurationApi | null, payload?: {
        enabled: boolean;
        onSuccess?: (enabled: boolean) => void;
    }) => {
        sharingConfiguration: SharingConfigurationApi | null;
        payload?: {
            enabled: boolean;
            onSuccess?: (enabled: boolean) => void;
        };
    };
    setPasswordRequired: (password_required: boolean) => boolean;
    setPasswordRequiredFailure: (error: string, errorObject?: any) => {
        error: string;
        errorObject?: any;
    };
    setPasswordRequiredSuccess: (sharingConfiguration: SharingConfigurationApi | null, payload?: boolean) => {
        sharingConfiguration: SharingConfigurationApi | null;
        payload?: boolean;
    };
    setSharingSettingsManualErrors: (errors: Record<string, any>) => {
        errors: Record<string, any>;
    };
    setSharingSettingsValue: (key: FieldName, value: any) => {
        name: FieldName;
        value: any;
    };
    setSharingSettingsValues: (values: DeepPartial<{
        hideExtraDetails: boolean;
        legend: boolean;
        noHeader: boolean;
        showInspector: boolean;
        theme: string;
        whitelabel: boolean;
    }>) => {
        values: DeepPartial<{
            hideExtraDetails: boolean;
            legend: boolean;
            noHeader: boolean;
            showInspector: boolean;
            theme: string;
            whitelabel: boolean;
        }>;
    };
    submitSharingSettings: () => {
        value: boolean;
    };
    submitSharingSettingsFailure: (error: Error, errors: Record<string, any>) => {
        error: Error;
        errors: Record<string, any>;
    };
    submitSharingSettingsRequest: (sharingSettings: {
        hideExtraDetails: boolean;
        legend: boolean;
        noHeader: boolean;
        showInspector: boolean;
        theme: string;
        whitelabel: boolean;
    }) => {
        sharingSettings: {
            hideExtraDetails: boolean;
            legend: boolean;
            noHeader: boolean;
            showInspector: boolean;
            theme: string;
            whitelabel: boolean;
        };
    };
    submitSharingSettingsSuccess: (sharingSettings: {
        hideExtraDetails: boolean;
        legend: boolean;
        noHeader: boolean;
        showInspector: boolean;
        theme: string;
        whitelabel: boolean;
    }) => {
        sharingSettings: {
            hideExtraDetails: boolean;
            legend: boolean;
            noHeader: boolean;
            showInspector: boolean;
            theme: string;
            whitelabel: boolean;
        };
    };
    togglePreview: () => {
        value: true;
    };
    touchSharingSettingsField: (key: string) => {
        key: string;
    };
    updateSettings: (settings: Record<string, any>) => Record<string, any>;
    updateSettingsFailure: (error: string, errorObject?: any) => {
        error: string;
        errorObject?: any;
    };
    updateSettingsSuccess: (sharingConfiguration: SharingConfigurationApi | null, payload?: Record<string, any>) => {
        sharingConfiguration: SharingConfigurationApi | null;
        payload?: Record<string, any>;
    };
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface sharingLogicMeta {
    key: string;
    __keaTypeGenInternalSelectorTypes: {
        siteUrl: (preflight: null | import("~/types").PreflightStatus) => string | undefined;
        whitelabelAvailable: (hasAvailableFeature: any) => any;
        accessControlAvailable: (hasAvailableFeature: any) => any;
        sharingAllowed: (currentOrganization: any) => boolean;
        params: (arg: any) => any;
        shareLink: (siteUrl: string | undefined, sharingConfiguration: SharingConfigurationApi | null, params: any) => string;
        embedLink: (siteUrl: string | undefined, sharingConfiguration: SharingConfigurationApi | null, params: any) => string;
        iframeProperties: (embedLink: string, iframeKey: number) => {
            allowFullScreen: true;
            frameBorder: number;
            height: string;
            key: number;
            sandbox: string;
            src: string;
            width: string;
        };
        embedCode: (iframeProperties: {
            allowFullScreen: true;
            frameBorder: number;
            height: string;
            key: number;
            sandbox: string;
            src: string;
            width: string;
        }) => string;
    };
}

export type sharingLogicType = MakeLogicType<sharingLogicValues, sharingLogicActions, SharingLogicProps, sharingLogicMeta>;

export const sharingLogic = kea<sharingLogicType>([
    path(['lib', 'components', 'Sharing', 'sharingLogic']),
    props({} as SharingLogicProps),
    key(
        ({ insightShortId, dashboardId, recordingId, notebookShortId }) =>
            `sharing-${insightShortId || dashboardId || recordingId || notebookShortId || ''}`
    ),
    connect(() => [preflightLogic, userLogic, dashboardsModel, organizationLogic]),

    actions({
        togglePreview: true,
        reloadIframe: true,
    }),
    reducers({
        showPreview: [true, { togglePreview: (state) => !state }],
        iframeKey: [0, { reloadIframe: (state) => state + 1 }],
    }),

    loaders(({ props }) => ({
        sharingConfiguration: [
            null as SharingConfigurationApi | null,
            {
                loadSharingConfiguration: async () => {
                    return await api.sharing.get(await propsToApiParams(props))
                },
                setIsEnabled: async ({
                    enabled,
                    onSuccess,
                }: {
                    enabled: boolean
                    onSuccess?: (enabled: boolean) => void
                }) => {
                    const sharingConfiguration = await api.sharing.update(await propsToApiParams(props), { enabled })
                    if (sharingConfiguration) {
                        onSuccess?.(Boolean(sharingConfiguration.enabled))
                    }
                    return sharingConfiguration
                },
                setPasswordRequired: async (password_required: boolean) => {
                    return await api.sharing.update(await propsToApiParams(props), {
                        password_required,
                    })
                },
                setAutoRefreshInterval: async (auto_refresh_interval: AutoRefreshIntervalEnumApi) => {
                    return await api.sharing.update(await propsToApiParams(props), {
                        auto_refresh_interval,
                    })
                },
                updateSettings: async (settings: Record<string, any>) => {
                    return await api.sharing.update(await propsToApiParams(props), { settings })
                },
            },
        ],
    })),
    listeners(({ props, values, actions }) => ({
        setIsEnabled: ({ enabled }) => {
            if (props.dashboardId) {
                eventUsageLogic.actions.reportDashboardShareToggled(props.dashboardId, enabled)
            }
        },
        setIsEnabledSuccess: () => {
            if (props.dashboardId) {
                dashboardsModel.actions.loadDashboards()
            }
        },
        setSharingSettingsValue: ({ name, value }) => {
            if (name === 'whitelabel' && props.dashboardId) {
                eventUsageLogic.actions.reportDashboardWhitelabelToggled(props.dashboardId, value)
            }
            if (name === 'whitelabel' && props.insightShortId) {
                eventUsageLogic.actions.reportInsightWhitelabelToggled(value)
            }
            // Auto-save all embed config changes to settings
            if (values.sharingConfiguration) {
                const savedSettings = values.sharingConfiguration.settings
                actions.updateSettings({
                    ...(savedSettings && typeof savedSettings === 'object' && !Array.isArray(savedSettings)
                        ? savedSettings
                        : {}),
                    [name as string]: value,
                })
            }
        },
        updateSettingsSuccess: () => {
            // Reload iframe when settings are updated
            actions.reloadIframe()
        },
        loadSharingConfigurationSuccess: (result) => {
            if (result) {
                // Load sharing settings from API into the form
                const savedSettings = result.sharingConfiguration?.settings || {}
                const formValues = {
                    ...defaultSharingSettings,
                    ...savedSettings,
                }
                actions.setSharingSettingsValues(formValues)
            }
        },
    })),

    forms({
        sharingSettings: {
            defaults: defaultSharingSettings,
        },
    }),
    selectors({
        siteUrl: [() => [preflightLogic.selectors.preflight], (preflight: null | import("~/types").PreflightStatus) => preflight?.site_url],

        whitelabelAvailable: [
            () => [userLogic.selectors.hasAvailableFeature],
            (hasAvailableFeature) => hasAvailableFeature(AvailableFeature.WHITE_LABELLING),
        ],
        accessControlAvailable: [
            () => [userLogic.selectors.hasAvailableFeature],
            (hasAvailableFeature) => hasAvailableFeature(AvailableFeature.ACCESS_CONTROL),
        ],

        sharingAllowed: [
            () => [organizationLogic.selectors.currentOrganization],
            (currentOrganization: OrganizationType) => currentOrganization?.allow_publicly_shared_resources ?? true,
        ],

        params: [
            () => [(_, props) => props.additionalParams],
            (additionalParams = {}) => ({
                ...additionalParams,
            }),
        ],

        shareLink: [
            (s) => [s.siteUrl, s.sharingConfiguration, s.params],
            (siteUrl: string | undefined, sharingConfiguration: SharingConfigurationApi | null, params) =>
                sharingConfiguration?.access_token
                    ? siteUrl + urls.shared(sharingConfiguration.access_token, params)
                    : '',
        ],

        embedLink: [
            (s) => [s.siteUrl, s.sharingConfiguration, s.params],
            (siteUrl: string | undefined, sharingConfiguration: SharingConfigurationApi | null, params) =>
                sharingConfiguration?.access_token
                    ? siteUrl + urls.embedded(sharingConfiguration.access_token, params)
                    : '',
        ],

        iframeProperties: [
            (s) => [s.embedLink, s.iframeKey],
            (embedLink: string, iframeKey: number) => ({
                width: defaultIframeConfig.width,
                height: defaultIframeConfig.height,
                frameBorder: 0,
                // React prop casing; embedCode lowercases keys, so the HTML snippet still reads "allowfullscreen"
                allowFullScreen: true,
                src: embedLink,
                key: iframeKey,
                sandbox: 'allow-scripts allow-same-origin allow-popups',
            }),
        ],

        embedCode: [
            (s) => [s.iframeProperties],
            (iframeProperties: {
    allowFullScreen: true;
    frameBorder: number;
    height: string;
    key: number;
    sandbox: string;
    src: string;
    width: string;
}) =>
                `<iframe ${Object.entries(iframeProperties)
                    .map(([key, value]) => {
                        if (value === true) {
                            return key.toLowerCase()
                        }
                        return `${key.toLowerCase()}="${String(value).split('"').join('')}"`
                    })
                    .join(' ')}></iframe>`,
        ],
    }),
    afterMount(({ actions }) => {
        actions.loadSharingConfiguration()
    }),
])
